version: '3.9'
volumes:
  php_socket:
services:
  nginx:
    image: nginx:latest
    ports:
      - 8090:80
    depends_on:
      - wordpress
    volumes:
      - php_socket:/var/run
      - ./nginx:/etc/nginx
      - ./wordpress/src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    container_name: nginx
  wordpress:
    image: wordpress:6.0.3-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - db
    volumes:
      - php_socket:/var/run
      - ./wordpress/src:/var/www/html
      - ./logs/wordpress/php:/var/log/php
      - ./php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    container_name: wordpress
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./logs/mysql:/var/lib/mysql
    container_name: db